/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CECT_Vistas;

import CECT_Modelos.CECTVehiculo;
import CECT_Modelos.CECTVehiculoDAO;
import CECT_Controladores.CECTMarcaControlador;
import CECT_Modelos.CECTMarcaDAO;
import CECT_Modelos.CECTMarca;

/**
 *
 * @author axele
 */
public class CECT_MDI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CECT_MDI.class.getName());

    /**
     * Creates new form CECT_MDI
     */
    public CECT_MDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        nuevaMarca = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        nuevaMotocicleta = new javax.swing.JMenuItem();
        maestroDetalle = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jMenu2.setText("Marcas");

        nuevaMarca.setText("Nueva Marca");
        nuevaMarca.addActionListener(this::nuevaMarcaActionPerformed);
        jMenu2.add(nuevaMarca);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vehiculos");

        nuevaMotocicleta.setText("Nuevo Vehiculo");
        nuevaMotocicleta.addActionListener(this::nuevaMotocicletaActionPerformed);
        jMenu3.add(nuevaMotocicleta);

        jMenuBar1.add(jMenu3);

        maestroDetalle.setText("Reportes");

        jMenuItem3.setText("Reportes");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        maestroDetalle.add(jMenuItem3);

        jMenuItem4.setText("MaestroDetalle");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        maestroDetalle.add(jMenuItem4);

        jMenuBar1.add(maestroDetalle);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaMarcaActionPerformed
        // TODO add your handling code here:
        CECT_FrmNuevaMarca nuevaMarcaForm = new CECT_FrmNuevaMarca();
        CECT_Modelos.CECTMarca marca = new CECTMarca();
        CECT_Modelos.CECTMarcaDAO dao = new CECTMarcaDAO();

        CECT_Controladores.CECTMarcaControlador controlador = new CECTMarcaControlador(marca, dao, nuevaMarcaForm);
        jDesktopPane1.add(nuevaMarcaForm);
        controlador.iniciar();
        nuevaMarcaForm.setVisible(true);
    }//GEN-LAST:event_nuevaMarcaActionPerformed

    private void nuevaMotocicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaMotocicletaActionPerformed
        // TODO add your handling code here:

        CECT_FrmNuevoVehiculo nuevaMotoForm = new CECT_FrmNuevoVehiculo();
        CECTVehiculo modelo = new CECTVehiculo();
        CECTVehiculoDAO dao = new CECTVehiculoDAO();

        CECT_Controladores.CECT_CtrlNuevoVehiculo ctrl = new CECT_Controladores.CECT_CtrlNuevoVehiculo(modelo, nuevaMotoForm, dao);

        jDesktopPane1.add(nuevaMotoForm);

        ctrl.iniciar();

        nuevaMotoForm.setVisible(true);
    }//GEN-LAST:event_nuevaMotocicletaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        CECT_Vistas.CECT_FrmReportes reportesForm = new CECT_Vistas.CECT_FrmReportes();
        CECT_Modelos.CECTReportesDAO dao = new CECT_Modelos.CECTReportesDAO();

        CECT_Controladores.CECTReportesControlador controlador = new CECT_Controladores.CECTReportesControlador(dao, reportesForm);
        jDesktopPane1.add(reportesForm);
        controlador.iniciar();

        reportesForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        CECT_Vistas.CECT_FrmMaestroDetalle vista = new CECT_Vistas.CECT_FrmMaestroDetalle();
        CECT_Modelos.CECTMaestroDetalleDAO dao = new CECT_Modelos.CECTMaestroDetalleDAO();

        CECT_Controladores.CECTMaestroDetalleControlador controlador = new CECT_Controladores.CECTMaestroDetalleControlador(dao, vista);

        jDesktopPane1.add(vista);
        controlador.iniciar();
        vista.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CECT_MDI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu maestroDetalle;
    private javax.swing.JMenuItem nuevaMarca;
    private javax.swing.JMenuItem nuevaMotocicleta;
    // End of variables declaration//GEN-END:variables
}
